# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02df8cb1f1953385b9db42562bc5829f1af2a5b65cf873581097885688c10b5fa406af420512964958cd75aa3ba2222be50920876df3f290340927737753fb4

test:
  secret_key_base: 889431365f69029a599c1cd1ec7cdec9f03195078f8ac2553e76d4857e397d8f0004599250098d4f6e1444df6e2f570ab32ea9f26561e564e6ba05b392c34308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
